name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build APK
      run:  |
        ./gradlew assembleRelease
        ./gradlew bundleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: FlickrBrowser.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
